class UserNotFoundException(Exception):
    pass

class UserAlreadyExistsException(Exception):
    pass
